// garlemald-server — Rust port of a FINAL FANTASY XIV v1.23b server emulator (lobby/world/map)
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Build script: pre-compress every `sql/seed/*.sql` migration file into
//! `$OUT_DIR/seed/<name>.gz` and emit a Rust source file, `seed_manifest.rs`,
//! that lists each `(name, compressed_bytes)` pair. `src/migrations.rs`
//! `include!`s the manifest so runtime code can iterate the static list
//! without pulling in any runtime crate for directory scanning.
//!
//! Gzipping matters because the seed set is ~18 MB of raw INSERT
//! statements with *heavy* repetition (column names, boilerplate), which
//! compresses to well under 1 MB. Baking the raw text into the binary
//! would pointlessly bloat every Garlemald server executable.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use flate2::Compression;
use flate2::write::GzEncoder;

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let seed_dir = manifest_dir.join("sql").join("seed");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let out_seed_dir = out_dir.join("seed");
    fs::create_dir_all(&out_seed_dir).expect("create $OUT_DIR/seed");

    println!("cargo:rerun-if-changed=sql/schema.sql");
    println!("cargo:rerun-if-changed=sql/seed");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<PathBuf> = fs::read_dir(&seed_dir)
        .unwrap_or_else(|e| panic!("read_dir({}): {e}", seed_dir.display()))
        .filter_map(|res| res.ok())
        .map(|ent| ent.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("sql"))
        .collect();
    entries.sort();

    let mut manifest = String::new();
    manifest.push_str(
        "// Auto-generated by build.rs — do not edit. Lists each bundled seed\n\
         // migration file as (name, gzip-compressed bytes). Iterate via\n\
         // `migrations::iter()`.\n\
         pub(crate) const SEED_MIGRATIONS: &[(&str, &[u8])] = &[\n",
    );

    for path in &entries {
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("utf-8 filename");
        let raw = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let mut enc = GzEncoder::new(Vec::new(), Compression::best());
        enc.write_all(&raw).expect("gz write");
        let compressed = enc.finish().expect("gz finish");
        let out_path = out_seed_dir.join(format!("{name}.gz"));
        fs::write(&out_path, &compressed)
            .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
        // `include_bytes!` paths are resolved relative to the .rs file that
        // contains the macro. The manifest is include!'d from
        // src/migrations.rs, so the path needs to start at OUT_DIR — we
        // use the absolute path which Cargo guarantees is stable across a
        // single build.
        manifest.push_str(&format!(
            "    ({name:?}, include_bytes!({:?})),\n",
            out_path.display().to_string(),
        ));
    }

    manifest.push_str("];\n");
    let manifest_path = out_dir.join("seed_manifest.rs");
    fs::write(&manifest_path, manifest).unwrap_or_else(|e| panic!("write manifest: {e}"));
}
